### ISSUE TITLE
Roz.kpi.ua parser does not parse all teachers

### ISSUE THREAD

**Issue by just-hoshinon** [fictadvisor/fictadvisor-api#285]
There are disciplines on the schedule, where mentioned two or more teachers (example below). Unfortunately, parser does not parse both teachers, only the first teacher is added to the database.

![opera_ZFLAaFj1Yv](https://user-images.githubusercontent.com/42845566/226207126-0dc14bb0-c9af-4f8c-9676-2458ead41a10.png)

Solution: fix parser to allow parse all teachers on the subject.

**Comment by nikolaichub** [comment]
could you name a few groups whose schedule have this issue? this would help me to fix this bug.

**Comment by just-hoshinon** [comment]
> could you name a few groups whose schedule have this issue? this would help me to fix this bug.

ІС-21, ІС-22, ІС-23
