### ISSUE TITLE
Parse teachers on subjects that is not mentioned on group schedule

### ISSUE THREAD

**Issue by just-hoshinon** [fictadvisor/fictadvisor-api#296]
There are cases, when teacher is not mentioned in the group schedule. The example below:

![image](https://user-images.githubusercontent.com/42845566/230740134-4ac93ae4-490b-4dee-b07a-9b1870734143.png)

As we can see, there are 4 selective disciplines, but only 3 teachers (the fourth is not here). Thus, the order of parsing is wrong and teachers will be connected not to their subjects.

Solution is check teacher schedule and check whether they are teaching this subject or not.

**Comment by basarabst** [comment]
Not planned
Closed
