### ISSUE TITLE
Add documentation for endpoint to get teacher statistics

### ISSUE THREAD

**Issue by OleksandrHumeniuk** [fictadvisor/fictadvisor-api#329]
Front-end team need to know the response for this endpoint to prepare the page. Please.

**Comment by just-hoshinon** [comment]
There is already a documentation of such endpoint in the teachers page ([/:teacherId/marks](https://github.com/fictadvisor/fictadvisor-api/wiki/Teachers#get-v2teachersteacherIdmarks)). But it's not full: there is no types mentioned. Also, depending on type there is another "mark" field type
