### ISSUE TITLE
Bug with sorting when resetting the sorting parameters

### ISSUE THREAD

**Issue by Lil5166** [fictadvisor/fictadvisor-api#465]
if you first sort teachers by some parameter
![image](https://github.com/fictadvisor/fictadvisor-api/assets/114685597/30ec8b72-cd3b-4731-93e8-5a89069cc402)
and then reset this parameter, it sorts randomly
![image](https://github.com/fictadvisor/fictadvisor-api/assets/114685597/94332cb5-e371-4e4c-b32e-78c94939f52f)

**Comment by basarabst** [comment]
The bug is automatically fixed by https://github.com/fictadvisor/fictadvisor-api/pull/525.
Closed
