### ISSUE TITLE
Add migration explanation to Wiki

### ISSUE THREAD

**Issue by basarabst** [fictadvisor/fictadvisor-api#560]
All members of our team must know how to perform database migration. However, beginners have difficulties with this. It may even be that the database will be cleared.

So it is suggested that we add a detailed explanation about this to our Wiki. Main theses:
- What exactly is migration?
- Algorithm for performing the task with migration (with an explanation of each script).
- Describe the risks associated with migration and how to avoid them.

**Comment by SharpDevOps10** [comment]
[Migration](https://github.com/fictadvisor/fictadvisor-api/wiki/Migration)

**Comment by basarabst** [comment]
Approved
