### ISSUE TITLE
Add Swagger documentation to Auth endpoints (2)

### ISSUE THREAD

**Issue by basarabst** [fictadvisor/fictadvisor-api#613]
Swagger documentation for endpoints is available on our project (https://apidev.fictadvisor.com/api - for dev). But many endpoints remain undescribed, which complicates the work of the frontend. 
Your task is to describe the Swagger endpoints below:

![image](https://github.com/fictadvisor/fictadvisor-api/assets/114052215/ba9133a6-2fac-4fba-b298-81298bc5fd64)

See example: https://github.com/fictadvisor/fictadvisor-api/pull/541

**Comment by Hahhhayam** [comment]
Move from fork to clone
