### ISSUE TITLE
Organize Wiki

### ISSUE THREAD

**Issue by basarabst** [fictadvisor/fictadvisor-api#645]
It's been quite some time since we switched to Swagger. We have old documentation left in the Wiki, which in most cases is not up-to-date. Your task is to remove documentation only for those endpoints that do **not exist** at all or are already **described** in Swagger.

![image](https://github.com/fictadvisor/fictadvisor-api/assets/114052215/89d06a4b-00bb-4738-b6a0-cdb2b69f0dcf)

It is **forbidden** to delete the documentation of env explaining, migrations and those endpoints whose description is not available in Swagger.

**Comment by JessFreak** [comment]
[Endpoints](https://github.com/fictadvisor/fictadvisor-api/wiki/Documentation#enpoints)

**Comment by basarabst** [comment]
approved
