### ISSUE TITLE
Create an explanation of merge conflicts and how to resolve them

### ISSUE THREAD

**Issue by fokaaas** [fictadvisor/fictadvisor-api#656]
Many backend beginners run into the problem of merge conflicts. But explaining to everyone how to do it takes a lot of time. So for better understanding and optimization of work, you should create a Wiki section using the following theses:
- What is a merge conflict?
- For what reasons does it occur?
- a step-by-step explanation of how it can be solved through the interface of popular IDE (2)

**Comment by SharpDevOps10** [comment]
[Merge Conflicts](https://github.com/fictadvisor/fictadvisor-api/wiki/Merge-conflicts)

**Comment by fokaaas** [comment]
Well done!
