### ISSUE TITLE
Add explanation about Swagger documentation in our project

### ISSUE THREAD

**Issue by fokaaas** [fictadvisor/fictadvisor-api#784]
You should describe the general practices and patterns we use. The explanation should be in the Wiki. Here are some theses:
- write about the main decorators
- write the order of their location in the controllers
- how to properly describe errors
- describe endpoint structure on the web page
- focus on describing fields and adding default values

**Comment by SharpDevOps10** [comment]
[Swagger prickol](https://github.com/fictadvisor/fictadvisor-api/wiki/Swagger-documentation)
